#!/usr/bin/env python
"""
End-to-end test: Convert mortenbra sample repo and verify generated services have real logic
"""
import os
import sys
import subprocess
import tempfile
import shutil
from pathlib import Path

# Add backend to path
sys.path.insert(0, str(Path(__file__).parent))

def run_conversion():
    """Run the full conversion pipeline"""
    print("=" * 80)
    print("Running full PL/SQL → Java conversion pipeline")
    print("=" * 80)
    
    # Run main.py with mortenbra sample
    cmd = [
        sys.executable, 
        "main.py",
        "--repo-url", "https://github.com/mortenbra/plsql-sample-code.git",
        "--config", "config.json"
    ]
    
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=Path(__file__).parent, capture_output=True, text=True, timeout=600)
    
    print("\n--- STDOUT ---")
    lines = result.stdout.split('\n')
    # Print last 50 lines
    for line in lines[-50:]:
        print(line)
    
    if result.stderr:
        print("\n--- STDERR (last 50 lines) ---")
        err_lines = result.stderr.split('\n')
        for line in err_lines[-50:]:
            print(line)
    
    print(f"\nReturn code: {result.returncode}")
    
    if result.returncode != 0:
        print("❌ Conversion failed")
        return None
    
    # Output goes to target/generated by default or check _tmp_proj
    possible_output_dirs = [
        Path(__file__).parent / "_tmp_proj" / "src" / "main" / "java",
        Path(__file__).parent / "target" / "generated" / "src" / "main" / "java",
        Path(__file__).parent / "build" / "generated" / "src" / "main" / "java",
    ]
    
    for output_dir in possible_output_dirs:
        if output_dir.exists():
            print(f"Found output at: {output_dir.parent.parent}")
            return str(output_dir.parent.parent)
    
    # Search more broadly
    for search_dir in [Path(__file__).parent]:
        for dir_path in search_dir.rglob("*Service.java"):
            output_dir = dir_path.parent.parent.parent  # Go up to src/main/java
            print(f"Found services at: {output_dir.parent.parent}")
            return str(output_dir.parent.parent)
    
    print("Could not find output directory - checking current directory")
    return Path(__file__).parent

def check_generated_services(output_dir):
    """Check if generated services have real logic"""
    if not output_dir:
        return False
    
    services_dir = Path(output_dir) / "src" / "main" / "java" / "com" / "example" / "service"
    
    if not services_dir.exists():
        print(f"❌ Services directory not found: {services_dir}")
        return False
    
    service_files = list(services_dir.glob("*Service.java"))
    print(f"\nFound {len(service_files)} service files")
    
    # Check specific services we expect
    test_services = {
        "InvoiceApiPkgCreateInvoiceService": ["validation", "calculation", "INSERT"],
        "CustomerPkgNewCustomerService": ["INSERT", "Repository"],
    }
    
    results = {}
    
    for service_file in service_files:
        content = service_file.read_text(encoding='utf-8')
        classname = service_file.stem
        
        print(f"\n[{classname}]")
        print(f"  File size: {len(content)} chars")
        
        # Check for empty stub indicators
        is_stub = content.count("TODO") > 2 or "throw new BusinessException" in content and content.count("{") < 5
        
        # Count actual code elements
        has_validation = "if (" in content or "if(" in content
        has_operation = "Repository" in content or "new " in content
        has_transactional = "@Transactional" in content
        has_insert = "INSERT" in content or "save(" in content
        has_logger = "logger" in content or "Logger" in content
        
        logic_count = sum([has_validation, has_operation, has_transactional, has_insert, has_logger])
        
        print(f"  Validation logic: {'✓' if has_validation else '✗'}")
        print(f"  Operation logic: {'✓' if has_operation else '✗'}")
        print(f"  @Transactional: {'✓' if has_transactional else '✗'}")
        print(f"  INSERT/save logic: {'✓' if has_insert else '✗'}")
        print(f"  Logger: {'✓' if has_logger else '✗'}")
        print(f"  Logic elements: {logic_count}/5")
        print(f"  Is stub: {'YES ❌' if is_stub else 'NO ✓'}")
        
        results[classname] = {
            'has_logic': logic_count >= 3 and not is_stub,
            'logic_count': logic_count,
            'is_stub': is_stub,
            'content': content
        }
    
    # Show sample of a specific service
    if service_files:
        print("\n" + "=" * 80)
        print("Sample: First service method body (truncated)")
        print("=" * 80)
        first_file = service_files[0]
        content = first_file.read_text()
        
        # Extract method body
        import re
        method_match = re.search(r'(public\s+\w+\s+\w+\s*\([^)]*\)\s*\{[^}]{0,500})', content, re.DOTALL)
        if method_match:
            print(method_match.group(1))
            print("...")
    
    return results

if __name__ == '__main__':
    print("Testing SBG-30: Full Pipeline E2E Verification\n")
    
    output_dir = run_conversion()
    
    if output_dir:
        results = check_generated_services(output_dir)
        
        print("\n" + "=" * 80)
        print("SUMMARY")
        print("=" * 80)
        
        if results:
            with_logic = sum(1 for r in results.values() if r['has_logic'])
            total = len(results)
            print(f"Services with real logic: {with_logic}/{total}")
            
            if with_logic == total and total > 0:
                print("\n✅ SUCCESS: All services have real business logic!")
                exit(0)
            else:
                print(f"\n❌ PARTIAL: Only {with_logic}/{total} services have logic")
                exit(1)
    else:
        print("\n❌ FAILED: Could not complete conversion")
        exit(1)
